<FiatScreen>:
    BoxLayout:
        orientation: 'vertical'

        Label:
            font_size: 50
            text: 'Total: {} {:,}'.format(app.fiat.mark, app.fiat.cent_to_dollar(root.payment_total))

        Label:
            font_size: 50
            text: 'Paid: {} {:,}'.format(app.fiat.mark, app.fiat.cent_to_dollar(root.payment_paid))

        Label:
            font_size: 50
            text: 'Change: {} {:,}'.format(app.fiat.mark, app.fiat.cent_to_dollar(root.payment_change))
