# CircleCI testing environment.
# Note: Installed Kivy version is different from production !

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:kivy-team/kivy-daily
            sudo apt-get install -y python3-kivy
            sudo pip install requests==2.21.0
      - run:
          name: config
          command: |
            sudo sh -c "echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen"
            sudo sh -c "echo 'fr_FR.UTF-8 UTF-8' >> /etc/locale.gen"
            sudo sh -c "echo 'ja_JP.UTF-8 UTF-8' >> /etc/locale.gen"
            sudo locale-gen
            sudo update-locale
            locale -a
      - run:
          name: run test
          command: |
            ./tests.sh
